### ISSUE TITLE
Bundle naming conflicts with parent / child themes

### ISSUE THREAD

**Issue by svandragt** [humanmade/asset-loader#27]
The entry bundle keys for environments must be unique, specifying the same key for a parent theme and a child theme means the parent bundle is not loaded.

Instead of prefixing entry bundle keys with `parent_` this scenario would be avoided if the environment name would be prepended to the final bunlde name, resulting in `$name-$bundle`.

Example of a problematic configuration (both the parent and child theme create a `styles` bundle):
```
module.exports = choosePort( 8080 ).then( port => [
	presets.development( {
		name: 'parent-theme',
		...shared,
		devServer : {
			...devServer,
			port,
		},
		entry: {
			styles: filePath( `${paths.theme_parent}/style.css` ),
		},
		output: {
			path: filePath( `${ paths.theme_parent }/build` ),
			publicPath: `https://${ host }:${ port }/parent-theme/`,
		},
	} ),
	presets.development( {
		name: 'child-theme',
		...shared,
		devServer : {
			...devServer,
			port,
		},
		entry: {
			styles: filePath( `${paths.theme_child}/style.css` ),
		},
		output: {
			path: filePath( `${ paths.theme_child }/build` ),
			publicPath: `https://${ host }:${ port }/child-theme/`,
		},
	} ),
```

**Comment by kadamwhite** [comment]
The entry also determines the asset name you would specify in `register_asset`, so altering it programmatically I worry would make it harder to correctly target the manifest item you need.

@svandragt can you elaborate on "the parent bundle is not loaded"? Are you able to share an example of the manifest (with client info redacted), and the Asset_Loader code used to enqueue that? I would imagine that a config like this would build one manifest in the parent theme, and one in the child theme, both with different bundles. In theory those should not conflict because the `output.path` is different. I'd like to see an example of the setup to understand what I might be overlooking.

If it does turn out to be an issue, I'd also like to consider adding a validation check to warn on duplicate keys, instead of rewriting names.

**Comment by kadamwhite** [comment]
@svandragt Following up here following @Sephsekla's push for a 1.0. Are you still experiencing an issue with this, and can you add more context if so?

**Comment by svandragt** [comment]
Entry handles are unique to a webpack configuration, not within the named environment in which they are declared. 
The scope was not clear at the time, and all the other declarations (`output`, `devServer`) are not replacing any existing configuration, so that's an anomaly.

**Comment by svandragt** [comment]
Let's close this, not blocking a 1.0 in any case.
